// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Starlight.Backend.Service;

#nullable disable

namespace Starlight.Backend.Migrations.Game
{
    [DbContext(typeof(GameDatabaseService))]
    partial class GameDatabaseServiceModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("AchievementUser", b =>
                {
                    b.Property<ulong>("AchievementsId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("OwnersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AchievementsId", "OwnersId");

                    b.HasIndex("OwnersId");

                    b.ToTable("AchievementUser");
                });

            modelBuilder.Entity("Starlight.Backend.Database.Game.Achievement", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("FavorText")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("Starlight.Backend.Database.Game.Score", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Accuracy")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("TotalPoints")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("TrackId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("Starlight.Backend.Database.Game.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("CurrentLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenTime")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("TotalExp")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("TotalPlayTime")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Starlight.Backend.Database.Game.UserSetting", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeyCode1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeyCode2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeyCode3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeyCode4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MasterVolume")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MusicVolume")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Offset")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoundEffectVolume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("AchievementUser", b =>
                {
                    b.HasOne("Starlight.Backend.Database.Game.Achievement", null)
                        .WithMany()
                        .HasForeignKey("AchievementsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Starlight.Backend.Database.Game.User", null)
                        .WithMany()
                        .HasForeignKey("OwnersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Starlight.Backend.Database.Game.Score", b =>
                {
                    b.HasOne("Starlight.Backend.Database.Game.User", "User")
                        .WithMany("BestScores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Starlight.Backend.Database.Game.User", b =>
                {
                    b.HasOne("Starlight.Backend.Database.Game.User", null)
                        .WithMany("Friends")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Starlight.Backend.Database.Game.UserSetting", b =>
                {
                    b.HasOne("Starlight.Backend.Database.Game.User", "User")
                        .WithOne("Setting")
                        .HasForeignKey("Starlight.Backend.Database.Game.UserSetting", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Starlight.Backend.Database.Game.User", b =>
                {
                    b.Navigation("BestScores");

                    b.Navigation("Friends");

                    b.Navigation("Setting");
                });
#pragma warning restore 612, 618
        }
    }
}
