name: Backend sanity check (C#)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/*.cs'
  pull_request_target:
    branches:
      - main
    types: [opened, reopened, synchronize, assigned]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Run tests
        run: dotnet test -c Release --nologo --no-restore